name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Type and format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 10.33.2

      - run: pnpm install
      - run: pnpm run format-check
      - run: pnpm run type-check
      - run: pnpm run test
